config/routes.rb
VotaPrato::Application.routes.draw do
  resources :comentarios

  resources :qualificacoes

  resources :clientes

  resources :main

  resources :restaurantes do
    resources :qualificacoes
  end

  resources :clientes do
    resources :qualificacoes
  end

  match '/mostra' => 'restaurantes#mostra'

  root :to => 'inicio#index'
  

end

app/models/restaurante.rb
#coding: utf-8

class Restaurante < ActiveRecord::Base
  attr_accessible :nome, :endereco, :especialidade

  def self.query_rapida
    self.select([:nome, :endereco, :especialidade])
  end

  # validates_presence_of :nome, :presence => true :message => 'Deve ser preenchido.'
  # validates_length_of :nome, :maximum => 80,
  #                     :message => 'A string excede o número máximo de caracteres.'
  validates :nome,  
          :presence => { :message => 'Deve ser preenchido.' },
          :length => { :maximum => 80, :message => 'muito grande' } #, :message => 'A string excede o número máximo de caracteres.' }
  
  # validates :nome,
  #       :uniqueness => { :scope => :estado } # ou :uniqueness => true

  validates_presence_of :endereco, :message => 'Deve ser preenchido.'

  validates :especialidade, :presence => {:message => 'Deve ser preenchido.'},
                            :length => { :maximum => 40,
                      :message => 'A string excede o número máximo de caracteres.'}

  validate :primeira_letra_deve_ser_maiuscula

  private
  def primeira_letra_deve_ser_maiuscula
    errors.add(:nome, 'primeira letra deve ser maiuscula!') unless nome =~ /\A[A-Z].*\z/
                                                                      # \A : primeiro caractere da strin
                                                                      # \z : último caractere da string
  end

  has_many :qualificacoes, :dependent => :destroy   #apaga as entradas das qualificações do restaurante em questão.
  has_and_belongs_to_many :pratos

  has_many :comentarios, as: :comentavel

  # Outros tipos de validação:
  # validates :sexo,
  #       :includsion => { :in => %w{m, f}}

  # validates :telefone,
  #       :format => {
  #             :with => REGEX
  #           }

  # validates :senha,
  #       :length => { in => 6..10,
  #             :too_short => 'Muito curto',
  #             :too_long => 'Muito longo'}

  # validates :idade,
  #       :numericality => {
  #         :only_integer => true
  #       }

  # Validações especiais
  # validates :termos_de_uso,
  #     :acceptance => true

  # validates :senha,
  #     :confirmation => true

end

app/controllers/restaurantes_controller.rb
class RestaurantesController < ApplicationController
  # layout 'premium', :only => [:new, :edit]  #:except => [:index]
  # before_filter :loga   # , :only => [:new, :show, :create]
  # after_filter :loga_de_novo
  # around_filter :around, :except => [:new]

  # respond_to :xml, :json, :html

  def index
    @restaurantes = Restaurante.order('nome').page(params['page']).per(3)
    # respond_to do |format|
    #   format.json { render :json => @restaurantes }
      # format.html { } # ação padrão
      # format.js   { head: 'ok' }
    # end
  end

  def show
    @restaurante = Restaurante.find(params[:id])
    flash[:alerta] = 'Cuidado! Flash boladao!'
    # respond_with @restaurante
  end

  def new
    @restaurante = Restaurante.new

    # Exibe layout de acordo com a condição
    # if 1 == 1
      # render :new, :layout => 'premium'
    # else
      render :new
    # end

    # respond_with @restaurante
  end

  def create
    @restaurante = Restaurante.new(params[:restaurante])
    if @restaurante.save
      redirect_to(action: 'show', id: @restaurante)
    else
      render :new
    end
  end

  def edit
    @restaurante = Restaurante.find(params[:id])
    # respond_with @restaurante
  end

  def update
    @restaurante = Restaurante.find(params[:id])
    if @restaurante.update_attributes(params[:restaurante])
      redirect_to(action: 'show', id: @restaurante) # ou redirect_to @restaurante
    else
      # render action: 'edit' # ou 
      render :edit
    end
  end

  def destroy
    @restaurante = Restaurante.find(params[:id])
    @restaurante.destroy

    redirect_to(action: 'index')
  end

  def mostra
    @coisa = Restaurante.first
  end

private
  def loga
    puts "*" * 100
  end

  def loga_de_novo
    puts "DE NOVO! " * 20
  end

  def around
    logger.debug 'oi'
    yield
    logger.info 'tchau'
  end
end

app/helpers/restaurantes_helper.rb
#encoding: utf-8

module RestaurantesHelper
  def boas_vindas
    if params[:user] == '1'
      return '<h2>Oi, usuário</h2>'.html_safe
    # else
    #   return '<h2>Quem é você?</h2>'.html_safe
    end
  end
end

app/views/restaurantes/_form.html.haml
= form_for restaurante do |f|
  Nome:
  = f.text_field :nome
  %br
  Endereço:
  = f.text_field :endereco
  %br
  Especialidade:
  = f.text_field :especialidade
  %br
  = f.submit 'Atualizar'

app/views/restaurantes/_restaurante.html.haml
%tr
  %td
    = restaurante.nome
  %td
    = restaurante.endereco
  %td
    = restaurante.especialidade
  %td
    = link_to 'Mostrar', action: 'show', id: restaurante
  %td
    = link_to 'Editar', action: 'edit', id: restaurante
  %td
    = link_to 'Deletar', restaurante_path(restaurante), method: :delete

app/views/restaurantes/edit.html.haml
%h1
  Editando Restaurante

- if @restaurante.errors.any?
  %ul
  - @restaurante.errors.full_messages.each do |msg|
    %li
      = msg

= render :partial => 'form', :locals => {:restaurante => @restaurante}

%br
= link_to 'Voltar', action: 'index'

app/views/restaurantes/index.html.haml
%h1
  Listagem de Restaurantes

%table.table.table-bordered.table-striped
  %tr
    %th
      Nome
    %th
      Endereço
    %th
      Especialidade

  = render :partial => 'restaurante', :collection => @restaurantes

= paginate @restaurantes

%br
= link_to 'Novo', action: 'new'

app/views/restaurantes/mostra.html.haml
= render :partial => 'form', :locals => {:restaurante => @coisa}

app/views/restaurantes/new.html.haml
%h1
  Adicionando Restaurante

- if @restaurante.errors.any?
  %ul
  - @restaurante.errors.full_messages.each do |msg|
    %li
      = msg

= render :partial => 'form', :locals => {:restaurante => @restaurante}


%br
= link_to 'Voltar', action: 'index'

app/views/restaurantes/show.html.haml
= flash[:alerta]
= boas_vindas
%h1
  Exibindo Restaurante

%p
  %b
    Nome
  = @restaurante.nome

%p
  %b
    Endereço
  = @restaurante.endereco

%p
  %b
    Especialidade
  = @restaurante.especialidade

%p
  %b
    Nota média:
  = @restaurante.qualificacoes.average(:nota)

%br

= link_to 'Qualificar este restaurante',  :controller => 'qualificacoes',
                                          :action => 'new',
                                          :restaurante => @restaurante
                                          
= link_to 'Editar', action: 'edit', id: @restaurante
= link_to 'Voltar', action: 'index'
#comentarios
  - unless @restaurante.comentarios.empty?
    = comentarios @restaurante
= novo_comentario(@restaurante)